FROM python:3.11-slim
WORKDIR /app

RUN pip install --no-cache-dir kafka-python psycopg2-binary python-dotenv

COPY s3_kafka_consumer_energi_db.py .
COPY validation.py .

CMD ["python", "s3_kafka_consumer_energi_db.py"]
